### ISSUE TITLE
Systray flashes

### ISSUE THREAD

**Issue by aviau** [copycat-killer/awesome-copycats#117]
Hello!

My systray flashes: icons appear and disapear..

Any idea what this could be caused by?

**Comment by copycat-killer** [comment]
How do you expect me to find out, if you don't provide any information?

Start again: provide me a way to reproduce the issue, give me a better description, including when it happens, for how much time it happens, and so on. If you can't localize the problem, paste me your `rc.lua`.

Come on, spend more than 2 seconds to write an issue report.

**Comment by aviau** [comment]
> How do you expect me to find out, if you don't provide any information?

Sorry, I was expecting you to ask questions. I am here to answer them. I don't really know what information is useful.

> when it happens

All the time, as soon as I login on my session.

> how much time it happens

The icons disappear for half a second, or for a full second, every 2 or 3 seconds.

If that helps, I have noticed that the icons are not just "invisible", they are really gone for half a second. By that I mean that if I right click on the location of the icons when they disappear, the context menu for that icon does not show up

Icons present:
![screenshot from 2016-08-03 12-45-19](https://cloud.githubusercontent.com/assets/2706882/17373881/2ab6c1e4-5978-11e6-9fbe-610bc29aa883.png)


Icons absent:
![screenshot from 2016-08-03 12-45-24](https://cloud.githubusercontent.com/assets/2706882/17373884/2d926f12-5978-11e6-9303-e579fb97f4a8.png)
.

**Comment by copycat-killer** [comment]
I don't see how my themes could affect the systray behavior, so we'll have to investigate.

Trivial question 1: which programs are those icons referred to?

Trivial question 2: does this happen also with default awesome theme?

> Sorry, I was expecting you to ask questions. I am here to answer them. I don't really know what information is useful.

Of course I'll ask you questions, but generally the protocol of reporting issues is to provide as much as possible informations about your problem in the first message. This way you speed up the process and spare some Q&A.

**Comment by aviau** [comment]
> Trivial question 1: which programs are those icons referred to?
nm-applet (left) and quasselclient (right).

> Trivial question 2: does this happen also with default awesome theme?

I could not reproduce.

However it looks like it is triggered by when I start using guake.

**Comment by copycat-killer** [comment]
I tried your `rc.lua`, without `insync start` and `sy gui` as autostart applications because I don't know what are those.

While I'm not having *flashes*, I experience a bit of flickering while spawning Guake trough `quake`. 

And the point is really that: **why do you use a *drop-down* application with a *drop-down* container?**

That causes a conflict, and the "flashes" may be the result of the two processes working one over the other. I don't see them probably because I have a faster cpu.

Plus, I don't know what your `sy gui` does, that could be a culprit too, judging by the fact that you aren't able to reproduce this behavior with the default configuration.

---

So, either use `guake` as autostart application, mapping its spawn to another key via its settings and **not** through `rc.lua`, or use another terminal application with `quake`. Since you like GTK+ ones, I suggest `termite`:

```lua
local quakeconsole = {}
for s = 1, screen.count() do
   quakeconsole[s] = lain.util.quake({ app = "termite", argname = "--name %s", wibox_height = 32})
end
```

**Comment by aviau** [comment]
> That causes a conflict, and the "flashes" may be the result of the two processes working one over the other.

It could be, but when I completely stop using quakeconsole and I just use guake normally, I get the same behaviour:

 - does not remember its size
 - icon flashes

The two behaviours I cannot reproduce when using the default awesome theme.


> That causes a conflict, and the "flashes" may be the result of the two processes working one over the other.

I would be happy to do that, but I have the problem above.

**Comment by copycat-killer** [comment]
Now that I think better about it, everything is clear.

Your issue is caused by the fact that my configs (like every other user's) don't have the floating layout for every screen.

Awesome default configuration, instead, has the floating layout for every screen.

So that's the point again: the floating layout doesn't arrange clients geometry, while every other layout does.

In your case, Guake not only obstructs `lain.util.quake`, but awesome itself: **it causes a sort of race condition**.

This explains why you can't reproduce the issues with default configuration.

---

After a quick search, I found out you're not the first one trying to use Guake with awesome. Some examples:

https://bbs.archlinux.org/viewtopic.php?id=174439
https://www.reddit.com/r/awesomewm/comments/40g4qp/awesomewm_guake_not_working_together
https://www.reddit.com/r/awesomewm/comments/rp9es/guake_in_awesome_wm

they all pervade the same thing: awesome and Guake together is a bad idea.

And that's because awesome is just a window manager, not the desktop environment Guake was meant for. So, you can't blame awesome if it can't cope with it easily.

---

If you don't want to give Guake up, you can [set awesome as GNOME window manager](https://awesome.naquadah.org/wiki/Quickly_Setting_up_Awesome_with_Gnome).

But if you don't want GNOME, then either you find out by yourself how to stick Guake and awesome together, or use a saner alternative, like the above cited `termite`.

In any case, your issue is nothing I can help you with, because it's not related to this repository.

I can not tell you anything else.

**Comment by aviau** [comment]
Thank you for all the details.

If I ever find a magic fix, I will make sure to report here ;)
