### ISSUE TITLE
lain.util.quake with konsole

### ISSUE THREAD

**Issue by shwsun** [copycat-killer/awesome-copycats#120]
Hi,

It just seems like quake is not working? ``Mod+z`` will not triggle the quake terminal. And I would say this project is awesome!

**Comment by copycat-killer** [comment]
Be more specific. If you are using a GTK+ terminal like `termite` or `gnome-terminal`, read [here](https://github.com/copycat-killer/awesome-copycats/issues/116).

Otherwise, paste me your `quake` configuration.

**Comment by shwsun** [comment]
Hmmm, I am using KDE5 + ArchLinux. And I am sure ``konsole`` is based on xterm. 

What do you mean by ``quake`` config?

**Comment by copycat-killer** [comment]
`konsole` is QT*-based application, not X-based.

I installed it for a trial, and [it's working fine here](https://linx.li/selif/a1wqd02o.png). You have just to do a proper set up. In order to do it, locate [this line](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.multicolor#L88) in your `rc.lua`, and change `app` value from `terminal` to `"konsole"`. This should be the result:

```lua
-- quake terminal
local quakeconsole = {}
for s = 1, screen.count() do
   quakeconsole[s] = lain.util.quake({ app = "konsole" })
end
```
If somehow this doesn't solve it, paste me your `rc.lua`.

**Comment by copycat-killer** [comment]
Anyway, since you're using KDE, I think it'd be saner to use [yakuake](https://yakuake.kde.org)  instead.

**Comment by shwsun** [comment]
Yes, ``app="konsole"`` or ``app="yakuake"`` works perfectly. Thank you very much!

**Comment by copycat-killer** [comment]
I did not mean to tell you to use `app="yakuake"` (that way, you're using a [dropdown application with a dropdown container](https://github.com/copycat-killer/awesome-copycats/issues/117#issuecomment-237485248)), but to use `yakuake` in place of `lain.util.quake`.

Since you seem to be a novice, I suggest you to read the awesome [wiki](https://awesomewm.org/wiki/Main_Page), especially [this page](https://awesomewm.org/wiki/My_first_awesome).
