### ISSUE TITLE
A little surprise with the Holo Theme.

### ISSUE THREAD

**Issue by Incognito4nonymous** [copycat-killer/awesome-copycats#125]
Hello again :smile: 
As I previously said, I work on an Awesome WM based interface for a Raspberry Pi, however I start the work on my laptop.
So, I decided to make some versions, one based on the Holo theme, and while I like to listen at some music when I make some computing, I noticed a little surprise with the Mpd widget, yes, that one again.
As far as I'm aware you have been listening some Vapor recently, you should give it a try with the Holo theme on, this one seems unable to handle Japanese characters, try it with 2 8 1 4, your desktop should be filled with :
`attempt to concatenate a userdata value`
I am really clueless about what the problem could be, but upon inspection, the code of Holo seems kinda different than the others.
That issue ain't present with other themes, it ain't also the font as I tried to replace it with Sans after it.
Also could you tell me how to add a background to widgets in Holo ?

**Comment by copycat-killer** [comment]
I am unable to reproduce.

![scrot](https://linx.li/selif/ogwncko7.png "Luke's test")

Are you sure this is not related to your MPD decoding?

Try adding [these settings](https://github.com/copycat-killer/dots/blob/master/.mpd/mpd.conf#L8-L9) in your `mpd.conf`.

If this doesn't solve it, try to figure out the exact steps needed to reproduce the issue (how to start mpd, which commands to execute, etc).

PS: If you're using `ncmpcpp`, in the browse section (default one, otherwise hit `1`) click `e` on a culprit song: if it says it can't open the file, then it's surely a decoding issue.

PS2: Also, spawn `mpc update` or press `u` in `ncmpcpp` before doing anything.

**Comment by Incognito4nonymous** [comment]
The song plays, but the problem is this : 
<a href="http://www.zimagez.com/zimage/screenshot2016-10-0218-25-38.php">
  <img src="http://www.zimagez.com/miniature/screenshot2016-10-0218-25-38.php" />
</a>
The problem ain't coming from mpd but from the theme itself.

**Comment by copycat-killer** [comment]
I see from the screenshot that your `ncmpcpp` doesn't render Japanese (thus not showing it), while `awesome.widget.tasklist` does (the bottom bar). You should investigate if your terminal about that, or set additional encoding options in `ncmpcpp` (see manual).

Also, you're missing some fonts in the taglist, you should add those too.

Back to the problem, first let's see if this is due to `wibox.widget.background`.

Remove [these lines](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.holo#L195-L222) and change [this line](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.holo#L403) like this:

```lua
 right_layout:add(mpdwidget)
```

Restart awesome and check.

**Comment by Incognito4nonymous** [comment]
> Also, you're missing some fonts in the taglist, you should add those too.

Yup, I'm currently adding the Dremora icons, still in w.i.p.
Nothing changed, still the same issue.

**Comment by copycat-killer** [comment]
Then, replace [those lines](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.holo#L171-L193) with these:

```lua
mpdwidget = lain.widgets.mpd({
    -- set other variables here if needed
    settings = function()
        artist = mpd_now.artist .. " "
        title  = mpd_now.title  .. " "

        if mpd_now.state == "pause" then
            artist = "mpd "
            title  = "paused "
        elseif mpd_now.state == "stop" then
            artist = ""
            title  = ""
        end

        widget:set_text(artist .. title)
    end
})
```

**Comment by Incognito4nonymous** [comment]
Thanks M8 !!!!

**Comment by copycat-killer** [comment]
The `markup.font` calls are not working with a blank space, in your case. If you wish to have the uppercases back, you can just remove them:

```lua
mpdwidget = lain.widgets.mpd({
    settings = function ()
        if mpd_now.state == "play" then
            mpd_now.artist = mpd_now.artist:upper():gsub("&.-;", string.lower)
            mpd_now.title = mpd_now.title:upper():gsub("&.-;", string.lower)
            widget:set_markup(markup.font("Tamsyn 8", string.format(" %s - %s ")))
            play_pause_icon:set_image(beautiful.pause)
        elseif mpd_now.state == "pause" then
            widget:set_markup(markup.font("Tamsyn 8", " MPD PAUSED "))
            play_pause_icon:set_image(beautiful.play)
        else
            widget:set_markup("")
            play_pause_icon:set_image(beautiful.play)
        end
    end
})
```

---

> Also could you tell me how to add a background to widgets in Holo ?

```lua
backgroundedwidget = wibox.widget.background()
backgroundedwidget:set_widget(mywidget)
backgroundedwidget:set_bgimage(widget_bg)
```

Be sure to add `backgroundedwidget` (instead of `mywidget`) to a wibox.

**Comment by Incognito4nonymous** [comment]
Thanks again for everything, it works flawlessly. :clap:
