### ISSUE TITLE
Changing mod4 + r/x support

### ISSUE THREAD

**Issue by fcevado** [copycat-killer/awesome-copycats#128]
There is any reason for the removal of Modkey r/x support?

**Comment by copycat-killer** [comment]
I removed `mod4 + x` with Lua prompt because the average user doesn't use it.

`mod4 + r` with `awful.widget.prompt:run()` has been substituted by `mod4 + x` with [dmenu](http://tools.suckless.org/dmenu), which is way more faster and powerful. I also chose `x` instead of `r` because is nearer to `mod4`, and so makes a faster combo. I use it a lot and love it. You should try it.

If you don't like it, you can always copy/paste the default code from `/etc/xdg/awesome/rc.lua`. These files are templates to customize, after all.

**Comment by fcevado** [comment]
Thanks. I'll try it.
Just two suggestions,
* would it be possible to keep the old config commented? i guess it would be easier for anyone to change it.
* would  it be possible to list all the dependencies needed? things dmenu, unclutter, mpd, etc(this ones i just remembered) and mention which are optionals.

If you agree, I can make a PR for both suggestions this weekend.

**Comment by copycat-killer** [comment]
Done.

**Comment by fcevado** [comment]
Thank you man. You're great!!! and really fast :heart_eyes:
