### ISSUE TITLE
xfce4-terminal Issues

### ISSUE THREAD

**Issue by acama** [copycat-killer/awesome-copycats#135]
Hi,
I am having some issues with xfce4-terminal when I use any of the awesome-copycats themes. xfce4-terminal opens fine but as soon as I try to change the layout of the screen ("mod + space"), the terminal's window goes dark and I can't see anything I type or any output from it. Refreshing awesome with "ctrl+mod+r" seems to make the terminal start acting normal again but as soon as I try to change the layout again I get the same issue. The current theme I am using now is "multicolor".
Note that I don't have any of these issues when I use the default awesome theme.

**Comment by copycat-killer** [comment]
I am unable to reproduce:

![20170121131019](https://cloud.githubusercontent.com/assets/1777696/22174295/01a3bec6-dfdb-11e6-880b-63cc471bc662.png)

You can try reverting back to original client focus, which is the only client related thing that I changed:

```diff
--- rc.lua
+++ rc.lua
@@ -872,15 +872,6 @@
 end)
 
--- No border for maximized clients
-client.connect_signal("focus",
-    function(c)
-        if c.maximized_horizontal == true and c.maximized_vertical == true then
-            c.border_width = 0
-        -- no borders if only 1 client visible
-        elseif #awful.client.visible(mouse.screen) > 1 then
-            c.border_width = beautiful.border_width
-            c.border_color = beautiful.border_focus
-        end
-    end)
+-- Default focus
+client.connect_signal("focus", function(c) c.border_color = beautiful.border_focus end)
 client.connect_signal("unfocus", function(c) c.border_color = beautiful.border_normal end)
 -- }}}
```
but I doubt it might be due to this: gtk terminals are known to not play well with window managers.

Try the patch above and tell me. Also, try testing with another gtk-based terminal. I suggest you to switch to `termite`, which is designed specifically to work with WMs, and also is definitely better than `xfce4-terminal`.

**Comment by acama** [comment]
I am not sure what the problem is with xfce4-terminal for me... However I have tried termite and it seems to work without any issues. Thanks for your help I will use termite from now on.

**Comment by copycat-killer** [comment]
You won't regret the switch at all.
