### ISSUE TITLE
Allow configuring awesome-copycats

### ISSUE THREAD

**Issue by aviau** [copycat-killer/awesome-copycats#153]
Hello!

It would be great if there was a way to make awesome-copycats configurable in a way that makes it easier to pull new changes.

I have been using the theme for years now, and I always find it troublesome to update to newer versions. I always end up taking the new version of the theme, and re-apply all of my changes manually. I wish I could just pull in recent changes with less effort, I would update the theme more often.

In the past, I had contributed a feature that made the theme modular (separated keybindings, variables, startup) in several files. It made it a bit easier to pull in new changes, but it slowed down loading time so it was not integrated after all.

By the way, I have just updated ( I was about a year behind ) and the improvements are great! I really love this theme :)

The kind of modifications I make to the theme are the following:
 - Set the variables in rc.lua (terminal and all...)
 - Change some theme variables in theme.lua
 - Add some startup apps
 - Change some keybindings
 - Add and configure some widgets, for example battery
 - Change default layouts
 - add rules

Do you have any ideas on how to approach this issue?

Is there a way I could do all of this, with very little modifications to rc.lua and theme.lua?

Could rc.lua or theme.lua load some sort of custom.lua where I can make those small changes?

For example, I am thinking of some themes/holo/theme.custom.lua where I can override ``theme.*`` vaiables without even touching theme.lua, allowing me to update theme.lua by just copying over the new one.

**Comment by copycat-killer** [comment]
> Is there a way I could do all of this, with very little modifications to rc.lua and theme.lua?

Basically you are asking how to customize a theme completely, but without putting your hands on code.

Unfortunately: every time a new major Awesome version comes out, there is an API break, so you have to redo your customizations. 

**But now it's easier.**

With this new modularization, you can

    Set the variables (terminal and all...)
    Add some startup apps
    Change some keybindings
    Change default layouts

in your `rc.lua`, and

    Add and configure some widgets, for example battery

in your `theme.lua`, so that you just need to change `chosen_theme` variable in `rc.lua` to preserve your preferences *and* switch the theme, instead of having N different `rc.lua` full of redundancy.

I suggest you to do as written [here](https://github.com/copycat-killer/awesome-copycats#usage) and to modify this line in `rc.lua` like this:

```diff
-local theme_path = string.format("%s/.config/awesome/themes/%s/theme.lua", os.getenv("HOME"), chosen_theme)
+local theme_path = string.format("%s/.config/awesome/themes/%s/theme-personal.lua", os.getenv("HOME"), chosen_theme)
```

then, copy `theme.lua` to `theme-personal.lua` and do your customizations here.

This way, any time you `git pull`, you won't lost anything.

**Comment by copycat-killer** [comment]
> For example, I am thinking of some` theme.custom.lua` where I can override theme variables  without even touching `theme.lua`, allowing me to update theme by just copying over the new one.

If you come up with a script for that, I'd merge it.
