### ISSUE TITLE
Ram usage when left on for long periods of time

### ISSUE THREAD

**Issue by bakakun028** [copycat-killer/awesome-copycats#175]
Tried this on three different systems with default rc.lua template and themes. Takes up huge amount of ram when left for long periods of time, eventually taking up more than 1GB over a course of few days.

**Comment by copycat-killer** [comment]
Some questions:

* Did you try with `/etc/xdg/awesome/rc.lua` too?

* What is your idle status? Are you sure it's due to awesome, and not to daemons or other processes?

* Are you able to define the exact steps to replicate this behaviour?

* What are your system specs?

FYI, you can clean your ram with

```shell
$ su
$ sync
$ echo 3 > /proc/sys/vm/drop_caches
```

**Comment by copycat-killer** [comment]
@bakakun028 Ping.

**Comment by copycat-killer** [comment]
@bakakun028 Another ping.

**Comment by copycat-killer** [comment]
Closing for no response.
