### ISSUE TITLE
[lain] calendar font & mpd widget setting 

### ISSUE THREAD

**Issue by CDitzel** [copycat-killer/awesome-copycats#186]
Do I have to install the fonts, icons etc. that are referenced at the bottom of the readme or are they installed automatically when cloning and installing the repo? I guess what Im trying to say is, why is says N/A where Icons are supoosed to be and why the calendar has bugs 

![img_20170611_173841](https://user-images.githubusercontent.com/22954412/27012284-248c4a14-4ecd-11e7-81a4-3d7ab14786fd.jpg)

**Comment by copycat-killer** [comment]
> Do I have to install the fonts, icons etc. that are referenced at the bottom of the readme

Yes.

> why is says N/A 

Because you don't use MPD or didn't configure it properly.

> why the calendar has bugs

Pick your choice:
- [read the wiki](https://github.com/copycat-killer/lain/wiki/calendar#notes)
- [#49](https://github.com/copycat-killer/lain/issues/49)
- [#17](https://github.com/copycat-killer/lain/issues/17)

If you have other questions, read the wikis and the issue sections first. Fill a new issue request **only** if you have a real issue.
