### ISSUE TITLE
several cities weather widget

### ISSUE THREAD

**Issue by fcevado** [copycat-killer/awesome-copycats#189]
i dont know if I should ask it here or at lain repo... but is it possible to make the weather widget work for several cities and cicle through them when clicking(like calendar works for changing months)?

**Comment by copycat-killer** [comment]
Yes, this is `lain` related.

`lain.widget.weather` uses Open Weather Map APIs, which offer [current weather data for multiple cities](http://openweathermap.org/current). Read `lain` wiki to know how to customize your widget in order to fetch it.

If you want forecasts too, OWM does not offer an API for fetching multiple at once (and I believe there's no free service capable of that at the moment), so you'll need to instantiate 2 different weather widgets. If you want to cycle through them, you can just create ad-hoc button signals.

**Comment by fcevado** [comment]
thanks :smile:
