### ISSUE TITLE
powerarrow-dark theme does not define a weather widget (so alt+w does nothing)

### ISSUE THREAD

**Issue by TapioT** [copycat-killer/awesome-copycats#193]
I noticed the powerarrow and powerarrow-dark themes do not define the weather widget. I fixed this by copying the definition from a different theme, but it might make sense to define a default weather widget in the rc.lua file.

**Comment by copycat-killer** [comment]
Default `theme.lua` just a store for simple variable, while my ones are more balanced due to modularity purposes, as described in the [readme](https://github.com/copycat-killer/awesome-copycats#usage).

The `lain` wiki is plenty of information, and the theme have all various examples, so it makes sense if you customise your templates as you like.
