### ISSUE TITLE
switch-theme.sh is dangerous!

### ISSUE THREAD

**Issue by myf** [copycat-killer/awesome-copycats#76]
I wanted to try out awesome copycat and try to figure out how certain them works so that I can incorporate certain elements into my own custome rc file. I have a few rc files that are sym-linked to `rc.lua`

HOWEVER, this `switch-theme.sh` over rights my own rc.lua file that I have been worked on forever with one of the rc files here. I now have to reconfigure from scratch. Please if you are thinking about trying their stuff out, back up your theme. and for the folks writing awesome-copycats, please write a line or warning or backing up their original rc.lua.

Thanks

**Comment by copycat-killer** [comment]
It's clearly written in the README that the script does just what [usage section suggests], plus pulling the latest commit.

Sorry to hear that, but you could have read carefully instead of blindly using the script.

I modified it to prevent this situation: now every switch also backups the previous configuration.

PS: I understand it's annoying now, but starting from scratch again will make you learn and meet your needs better.
